### ISSUE TITLE
Problem with get

### ISSUE THREAD

**Issue by konorlevich** [linslin/Yii2-Curl#58] opened 2017-03-20 12:18 UTC
I have upgraded linslin/yii2-curl from 1.0.3 to 1.1.1

My request

```php
        $curl = new Curl();
        $curl->setOption(CURLOPT_HEADER, 'Accept:application/json');
        $response = $curl->get($url);
```

in function _httpRequest we have 

```php
        //extract header / body data if CURLOPT_HEADER are set to true
        if (isset($curlOptions[CURLOPT_HEADER]) && $curlOptions[CURLOPT_HEADER]) {
            $this->response = $this->_extractCurlBody($response);
            $this->responseHeaders = $this->_extractCurlHeaders($response);
        } else {
            $this->response = $response;
        }
```
and 
```php
protected function _extractCurlBody ($response)
    {
        return substr($response, $this->getInfo(CURLINFO_HEADER_SIZE));
    }
```

in my response I have

```php
'getInfo(CURLOPT_HEADER)' => false
'getInfo(CURLINFO_HEADER_SIZE)' => 503
```

Then cURL returns my response without half of it
But without 
```php
$curl->setOption(CURLOPT_HEADER, 'Accept:application/json');
``` 
I have full response

What am i doing wrong?

**Comment by linslin** [comment] 2017-03-20 12:36
HI @konorlevich, thanks for you request.  Just for refactoring since 1.1.1 you can use the following syntax to setup your cURL request:

```
$curl = new curl\Curl();
$response = $curl->setHeaders([
        'accept' => 'application/json'
     ])
     ->get($url);
```
It seems like the header size provided by `CURLINFO_HEADER_SIZE` does not match to the real response header size in your request. Could you add your response headers & body to make it reproduceable?

**Comment by konorlevich** [comment] 2017-03-20 12:53
Yes, of course
```php
[
    'file_get_contents($url)' =>  '[{\"id\":28,\"asset_id\":53,\"parent_id\":27,\"lft\":68,\"rgt\":69,\"level\":2,\"path\":\"peoplehavaet/usaboxoffice\",\"title\":\"Бокс-офис США\",\"alias\":\"usaboxoffice\",\"new_path\":\"box-office/usa\",\"note\":\"\",\"description\":\"\",\"extension\":\"com_content\",\"published\":1,\"checked_out\":0,\"checked_out_time\":null,\"access\":1,\"params\":\"{}\",\"metadesc\":\"\",\"metakey\":\"\",\"metadata\":\"\",\"created_user_id\":0,\"created_time\":\"2012-01-02 14:26:35\",\"modified_user_id\":0,\"modified_time\":\"2016-07-25 17:41:19\",\"hits\":0,\"language\":\"*\",\"is_active\":1,\"catsort\":null},{\"id\":31,\"asset_id\":56,\"parent_id\":27,\"lft\":74,\"rgt\":75,\"level\":2,\"path\":\"peoplehavaet/ruboxoffice\",\"title\":\"Бокс-офис России\",\"alias\":\"ruboxoffice\",\"new_path\":\"box-office/russia\",\"note\":\"\",\"description\":\"\",\"extension\":\"com_content\",\"published\":1,\"checked_out\":0,\"checked_out_time\":null,\"access\":1,\"params\":\"{}\",\"metadesc\":\"\",\"metakey\":\"\",\"metadata\":\"\",\"created_user_id\":0,\"created_time\":\"2012-01-02 14:26:35\",\"modified_user_id\":0,\"modified_time\":\"2016-07-25 17:41:18\",\"hits\":0,\"language\":\"*\",\"is_active\":1,\"catsort\":null}]'
    '$curl->getInfo(CURLOPT_HEADER)' => false
    '$curl->getInfo(CURLINFO_HEADER_SIZE)' => 502
    '$curl->responseHeaders' => [
        'http_code' => ''
    ]
    '$curl->responseCode' => 200
    '$curl->get($url)' => 'is_active\":1,\"catsort\":null},{\"id\":31,\"asset_id\":56,\"parent_id\":27,\"lft\":74,\"rgt\":75,\"level\":2,\"path\":\"peoplehavaet/ruboxoffice\",\"title\":\"Бокс-офис России\",\"alias\":\"ruboxoffice\",\"new_path\":\"box-office/russia\",\"note\":\"\",\"description\":\"\",\"extension\":\"com_content\",\"published\":1,\"checked_out\":0,\"checked_out_time\":null,\"access\":1,\"params\":\"{}\",\"metadesc\":\"\",\"metakey\":\"\",\"metadata\":\"\",\"created_user_id\":0,\"created_time\":\"2012-01-02 14:26:35\",\"modified_user_id\":0,\"modified_time\":\"2016-07-25 17:41:18\",\"hits\":0,\"language\":\"*\",\"is_active\":1,\"catsort\":null}]'
]
```

Do you need any other information?

**Comment by linslin** [comment] 2017-03-20 12:59
Could you give me the full output of `$curl->getInfo()` ?

**Comment by konorlevich** [comment] 2017-03-20 13:24
```php
'$curl->getInfo()' => [
        'url' => 'http://backend.local/v1/categories?per-page=2'
        'content_type' => 'application/json; charset=UTF-8'
        'http_code' => 200
        'header_size' => 502
        'request_size' => 114
        'filetime' => -1
        'ssl_verify_result' => 0
        'redirect_count' => 0
        'total_time' => 0.013927
        'namelookup_time' => 0.004129
        'connect_time' => 0.004187
        'pretransfer_time' => 0.004218
        'size_upload' => 0
        'size_download' => 1068
        'speed_download' => 76685
        'speed_upload' => 0
        'download_content_length' => 1068
        'upload_content_length' => -1
        'starttransfer_time' => 0.013912
        'redirect_time' => 0
        'redirect_url' => ''
        'primary_ip' => '127.0.1.1'
        'certinfo' => []
        'primary_port' => 80
        'local_ip' => '127.0.0.1'
        'local_port' => 40332
    ]
```

**Comment by linslin** [comment] 2017-03-20 14:15
Thx! I need to add a param to get the raw response for debugging. Well, could you add `var_dump($response);die();` for debugging output in line 519 in `linslin\yii2-curl\Curl.php` and add the full raw output here?

**Comment by konorlevich** [comment] 2017-03-20 14:20
string(7314) "HTTP/1.1 200 OK Date: Mon, 20 Mar 2017 14:17:46 GMT Server: Apache/2.4.18 (Ubuntu) X-Pagination-Total-Count: 13 X-Pagination-Page-Count: 1 X-Pagination-Current-Page: 1 X-Pagination-Per-Page: 50 Link: <http://backend.local/v1/categories?per-page=50&page=1> ; rel=self Content-Length: 6960 Content-Type: application/json; charset=UTF-8 [{"id":28,"asset_id":53,"parent_id":27,"lft":68,"rgt":69,"level":2,"path":"peoplehavaet/usaboxoffice","title":"Бокс-офис США","alias":"usaboxoffice","new_path":"box-office/usa","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":0,"modified_time":"2016-07-25 17:41:19","hits":0,"language":"*","is_active":1,"catsort":null},{"id":31,"asset_id":56,"parent_id":27,"lft":74,"rgt":75,"level":2,"path":"peoplehavaet/ruboxoffice","title":"Бокс-офис России","alias":"ruboxoffice","new_path":"box-office/russia","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":0,"modified_time":"2016-07-25 17:41:18","hits":0,"language":"*","is_active":1,"catsort":null},{"id":17,"asset_id":42,"parent_id":1,"lft":25,"rgt":46,"level":1,"path":"bigmovie","title":"Кино","alias":"bigmovie","new_path":"movies","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{\"category_layout\":\"\",\"image\":\"\"}","metadesc":"","metakey":"","metadata":"{\"author\":\"\",\"robots\":\"\"}","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":62,"modified_time":"2016-08-24 13:55:26","hits":0,"language":"*","is_active":1,"catsort":1},{"id":27,"asset_id":52,"parent_id":1,"lft":67,"rgt":80,"level":1,"path":"peoplehavaet","title":"Кинокасса","alias":"boxoffice","new_path":"box-office","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{\"category_layout\":\"\",\"image\":\"\"}","metadesc":"","metakey":"","metadata":"{\"author\":\"\",\"robots\":\"\"}","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":62,"modified_time":"2016-08-24 13:55:26","hits":0,"language":"*","is_active":1,"catsort":3},{"id":7,"asset_id":32,"parent_id":1,"lft":47,"rgt":56,"level":1,"path":"tv","title":"Сериалы","alias":"tv","new_path":"tv","note":" ","description":" ","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{\"category_layout\":\"\",\"image\":\"\"}","metadesc":" ","metakey":" ","metadata":"{\"author\":\"\",\"robots\":\"\"}","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":62,"modified_time":"2016-08-24 13:55:26","hits":0,"language":"*","is_active":1,"catsort":3},{"id":18,"asset_id":43,"parent_id":17,"lft":26,"rgt":27,"level":2,"path":"bigmovie/movienews","title":"Новости","alias":"movienews","new_path":"movies/news","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":0,"modified_time":"2016-07-25 17:41:03","hits":0,"language":"*","is_active":1,"catsort":4},{"id":23,"asset_id":48,"parent_id":17,"lft":38,"rgt":39,"level":2,"path":"bigmovie/rezenzii","title":"Рецензии","alias":"rezenzii","new_path":"movies/reviews","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":16,"modified_time":"2016-10-03 15:44:27","hits":0,"language":"*","is_active":1,"catsort":5},{"id":20,"asset_id":45,"parent_id":17,"lft":30,"rgt":31,"level":2,"path":"bigmovie/postery","title":"Постеры","alias":"postery","new_path":"movies/posters","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{\"category_layout\":\"\",\"image\":\"\"}","metadesc":"","metakey":"","metadata":"{\"author\":\"\",\"robots\":\"\"}","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":62,"modified_time":"2016-07-25 17:41:06","hits":0,"language":"*","is_active":1,"catsort":6},{"id":19,"asset_id":44,"parent_id":17,"lft":28,"rgt":29,"level":2,"path":"bigmovie/trailers","title":"Трейлеры","alias":"trailers","new_path":"movies/trailers","note":"","description":"","extension":"com_content","published":1,"checked_out":163,"checked_out_time":"2016-04-08 17:22:05","access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":0,"modified_time":"2016-07-25 17:41:14","hits":0,"language":"*","is_active":1,"catsort":7},{"id":8,"asset_id":33,"parent_id":7,"lft":48,"rgt":49,"level":2,"path":"tv/tvnews","title":"Новости","alias":"news","new_path":"tv/news","note":"","description":"
","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":0,"modified_time":"2016-07-25 17:41:24","hits":0,"language":"*","is_active":1,"catsort":8},{"id":9,"asset_id":34,"parent_id":7,"lft":50,"rgt":51,"level":2,"path":"tv/mnenie","title":"Рецензии","alias":"mnenie","new_path":"tv/reviews","note":"","description":"
","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":0,"modified_time":"2016-07-25 17:41:23","hits":0,"language":"*","is_active":1,"catsort":9},{"id":10,"asset_id":3866,"parent_id":7,"lft":52,"rgt":53,"level":2,"path":"tv/postery","title":"Постеры","alias":"postery","new_path":"tv/posters","note":"","description":"","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{\"category_layout\":\"\",\"image\":\"\"}","metadesc":"","metakey":"","metadata":"{\"author\":\"\",\"robots\":\"\"}","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":62,"modified_time":"2016-07-25 17:41:24","hits":0,"language":"*","is_active":1,"catsort":10},{"id":11,"asset_id":36,"parent_id":7,"lft":54,"rgt":55,"level":2,"path":"tv/tvpreview","title":"Трейлеры","alias":"tvpreview","new_path":"tv/trailers","note":"","description":"
","extension":"com_content","published":1,"checked_out":0,"checked_out_time":null,"access":1,"params":"{}","metadesc":"","metakey":"","metadata":"","created_user_id":0,"created_time":"2012-01-02 14:26:35","modified_user_id":0,"modified_time":"2016-08-25 20:33:08","hits":0,"language":"*","is_active":1,"catsort":11}]"

**Comment by linslin** [comment] 2017-03-20 14:30
Yea, crazy. The header size does not match with the characters in the header.

**Comment by linslin** [comment] 2017-03-20 14:32
Which PHP version are you using?

**Comment by konorlevich** [comment] 2017-03-20 14:44
PHP Version 7.0.15-0ubuntu0.16.10.4

**Comment by linslin** [comment] 2017-03-20 14:48
Allright, thx. I will take some time to create a test for this case. Please hang on. It will maybe take some days for me.

**Comment by konorlevich** [comment] 2017-03-20 14:50
Thank you.

**Comment by linslin** [comment] 2017-03-29 08:54
Sorry, still unable to reproduce it. We looking straight forward to fix this in v1.1.3.

**Comment by linslin** [comment] 2017-06-11 10:36
@konorlevich could you provide an URL/API/ENDPOINT where this happends? I'm still unable to reproduce this problem with my endpoints.

**Comment by linslin** [comment] 2017-06-13 10:47
I going to close this issue. Once you bring some feedback I will reopen it.

**Closed by linslin** 2017-06-13 10:47 UTC
Labels: bug, help wanted

**Comment by konorlevich** [comment] 2017-06-21 13:33
Sorry, but I don't have access to that code anymore
Thank you
